name: Books CI

on:
  push:
    branches: [ "main" ]
    paths:
      # ONLY trigger when files in the Books folder change
      - 'Books/**' 
      # Also trigger if you update this specific workflow file
      - '.github/workflows/books-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      # ONLY trigger when files in the Books folder change
      - 'Books/**' 
      # Also trigger if you update this specific workflow file
      - '.github/workflows/books-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Books

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" # Caches dependencies to speed up future runs

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with Pytest
        run: |
          pytest
